---
- hosts: all
  become: true
  tasks:

    - name: install apache2 package with php support
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
