---
- hosts: all
  become: true
  pre_tasks:

    - name: install updates for rocky
      tags: always
      ansible.builtin.dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "Rocky"

    - name: install updates for debian
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"


- hosts: all
  become: true
  roles:
    - base

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: apache
  become: true
  roles:
    - geerlingguy.apache
