---
- name: install apache on web servers (debian)
  tags: apache, debian
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_distribution == "Debian"

- name: install apache on web servers (rocky)
  tags: apache, rocky
  ansible.builtin.dnf:
    name:
      - httpd
      - php
  when: ansible_distribution == "Rocky"

- name: ensure apache is running (debian)
  tags: apache, debian
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_distribution == "Debian"

- name: ensure apache is running (rocky)
  tags: apache, rocky
  ansible.builtin.service:
    name: httpd
    state: started
  when: ansible_distribution == "Rocky"

- name: change email address for admin
  tags: apache, rocky
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: 'ServerAdmin admin@applepark.home'
    backup: yes
  when: ansible_distribution == "Rocky"
  register: httpd

- name: restart httpd (rocky)
  tags: apache, rocky
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy html file for site
  tags:
    - apache
    - debian
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
    backup: yes
